### ISSUE TITLE
v0.10.1 gives errors "version `GLIBC_2.3X' not found (required by /app/kustomize-kcl)"

### ISSUE THREAD

**Issue by Stinjul** [kcl-lang/kustomize-kcl#16]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Follow the steps in the [Kustomize KCL Plugin](https://www.kcl-lang.io/docs/user_docs/guides/working-with-k8s/mutate-manifests/kustomize-kcl-plugin) guide
Before running kustomize, change the image version in the KCLRun resource to v0.10.1
Run the kustomize fn command in the guide

### 2. What did you expect to see? (Required)

The same yaml files as in the guide.

### 3. What did you see instead (Required)

```
/app/kustomize-kcl: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /app/kustomize-kcl)
/app/kustomize-kcl: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /app/kustomize-kcl)
/app/kustomize-kcl: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /app/kustomize-kcl)
Error: exit status 1
```

### 4. What is your KCL components version? (Required)

docker.io/kcllang/kustomize-kcl:v0.10.1

### Extra Info
v0.9.0 and lower all work fine, just not v0.10.1

**Comment by Peefy** [comment]
I've disabled CGO in the v0.10.2 kustomize-kcl image, can you try again?

**Comment by Stinjul** [comment]
It works now, thanks!
